[project]
name = "bib2txt"
version = "0.1.0"
description = "Minimal Python utility displaying a BibTeX file as plaintext, mainly for use with LLMs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bibtexparser>=1.4.3",
    "pylatexenc>=2.10",
]
